language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk
  - Squeak-5.0
  - Squeak-4.6

baseline:
  - SWTDemo

os:
  - linux
  - osx

env:
  global:
    - BASELINE_GROUP="TravisCI"
    - PACKAGES="packages"
