language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk

#baseline: SWTDemo

os:
  - linux

env:
  global:
    - BASELINE="SWTDemo"
    - BASELINE_GROUP="TravisCI"
    - PACKAGES="packages"

before_install:
  - printenv
  - cd "$SMALLTALK_CI_HOME"
  - ls -lisa
