language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk

#baseline: SWTDemo

os:
  - linux

env:
  global:
    - BASELINE="SWTDemo"
    - BASELINE_GROUP="TravisCI"
    - PACKAGES="packages"

script: $SMALLTALK_CI_HOME/run.sh -v
